apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vendere-core-be-ingress
  annotations:
    meta.helm.sh/release-name: vendere-core-be
    meta.helm.sh/release-namespace: default
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: api.vendere.store
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vendere-core-be-service
                port:
                  number: 80
{{/*  tls:*/}}
{{/*    - hosts:*/}}
{{/*        - api.vendere.store*/}}
{{/*      secretName: vendere-api-tls*/}}
