# Chart.yaml
apiVersion: v2
name: vendere-core-be
description: A Helm chart for vendere-core backend
type: application
version: 0.1.0
appVersion: "1.0.0"


dependencies:
  - name: ingress-nginx
    version: "4.0.6"  # Specify the version of the ingress-nginx chart you wish to use
    repository: "https://kubernetes.github.io/ingress-nginx"
    condition: ingress-nginx.enabled
